---
- hosts: all
  remote_user: ubuntu
  vars:
    home_path: "{{ ansible_env.HOME}}"
    sneezly_repo_path: "{{ home_path }}/sneezly"
    sneezly_app_path: "{{ sneezly_repo_path }}/sneezly"
    sneezly_env_path: "{{ home_path }}/venvs/sneezly_env"
    sneezly_static_path: "{{ sneezly_app_path }}/collectstatic"
    daphne_port: 8080
    nginx_port: 80
    database_name: sneezly
    database_username: ejm
  tasks:
  - name: Include secret variables
    include_vars:
      file: secrets.yml
      name: secrets
  - name: Install system packages
    apt:
      name: "{{item}}"
      state: installed
    with_items:
      - virtualenv
      - redis-server
      - postgresql
      - nginx
      - libpq-dev
      - python-psycopg2
      - python
      - python-pip
    become: true
  - name: Install system python packages
    pip:
      name: "{{item}}"
      state: latest
      executable: pip2
    with_items:
      - pip
      - psycopg2
      - supervisor
    become: true
  - name: Start redis server
    service:
      name: redis-server
      state: started
    become: true
  - name: Start postgresql server
    service:
      name: postgresql
      state: started
    become: true
  - name: Clone sneezly repository
    git:
      repo: https://github.com/eddiejessup/sneezly.git
      dest: "{{ sneezly_repo_path }}"
      accept_hostkey: true
  - name: Make sneezly virtualenv
    pip:
      name: pip
      state: latest
      virtualenv: "{{ sneezly_env_path }}"
      virtualenv_python: python3.5
  - name: Install python packages for sneezly app
    pip:
      requirements: "{{ sneezly_app_path }}/requirements.txt"
      executable: /home/ubuntu/venvs/sneezly_env/bin/pip
  - name: Render and copy sneezly app deployment settings template
    template:
      src: settings.ini
      dest: "{{ sneezly_app_path }}/sneezly/"
  - name: Create sneezly app database
    postgresql_db:
      name: "{{ database_name }}"
    become: true
    become_user: postgres
  - name: Create sneezly app database user and grant privileges
    postgresql_user:
      name: "{{ database_username }}"
      password: "{{ secrets['database_password'] }}"
      db: "{{ database_name }}"
      priv: ALL
    become: true
    become_user: postgres
  - name: Run sneezly Django migrations, and collect static files
    django_manage:
      command: "{{ item }}"
      app_path: "{{ sneezly_app_path }}"
      virtualenv: "{{ sneezly_env_path }}"
    with_items:
      - migrate
      - collectstatic
  - name: Render and copy supervisor daemon configuration file template
    template:
      src: supervisord.conf
      dest: /etc/
    become: true
  - name: Copy supervisor daemon systemd script
    copy:
      src: supervisord.service
      dest: /etc/systemd/system/
    become: true
  - name: Restart supervisor daemon
    systemd:
      name: supervisord
      state: restarted
      daemon_reload: yes
    become: true
  - name: Remove default nginx site configuration
    file:
      path: /etc/nginx/sites-enabled/default
      state: absent
    become: true
  - name: Render and copy nginx site configuration template
    template:
      src: nginx.conf
      dest: /etc/nginx/sites-enabled/sneezly
    become: true
  - name: Restart nginx server
    service:
      name: redis-server
      state: restarted
    become: true
